name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Unit & E2E
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: recursive

    - run: git checkout HEAD^2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: database-dev
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start Databases
      run:  |
        docker compose up -d
        sleep 10

    - name: Run Tests
      run: |
        arch=$(uname -m)
        if [ "${arch}" = "amd64" ]; then 
            docker compose exec tests vendor/bin/phpunit --configuration phpunit.xml --testsuite X86;
        elif [ "${arch}" = "arm64" ] || [ "${arch}" = "aarch64" ]; then
            docker compose exec tests vendor/bin/phpunit --configuration phpunit.xml --testsuite ARM64; 
        fi