name: "Tests"

on: [pull_request]


jobs: 
    test:
        name: "Unit & E2E Test"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.0', '8.0', '8.0.23','nightly']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 2  
            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.25.5
              with: 
                php-version: ${{matrix.php-versions}}
            - name: Install dependencies
              run: composer install --ignore-platform-reqs
            - name: Analyse code
              run: composer analyse
            - name: Run Tests
              run:  composer test
