name: "Tests"

on: [pull_request, push]


jobs: 
    test:
        name: "Unit & E2E Test"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 2  
            - name: Run Tests
              run: |
                docker run --rm --interactive -v $PWD:/app composer sh -c \
                "composer install --profile --ignore-platform-reqs && composer test"
